# authentication credentials
credentials:
  usernames:
    Piyal:
      email: piyal@gmail.com
      name: Piyal Dey
      password: $2b$12$.9wlECTAivmpbLnMais66uDV0WMjjk6dWosWPXL/u81VH0.wiaQi.

cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
  - piyal@growwithdata.net




db:
  host: "127.0.0.1"
  user: "abstract-programmer"
  passwd: "example-password"
  database: "ExpenseDB"
  auth_plugin: "mysql_native_password"


email_sender:
  email: "kalim.resource@gmail.com"
  pass: "abc"